apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: jvmopts-operator
  name: jvmopts-operator-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: jvmopts-operator
