apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - namespaces
  - configmaps
  - pods/log
  verbs:
  - '*' 
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
