apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: javaopts-viewer-role
rules:
- apiGroups:
  - cpe.benchmark.io
  resources:
  - javaopts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cpe.benchmark.io
  resources:
  - javaopts/status
  verbs:
  - get
