kind: Service
apiVersion: serving.knative.dev/v1
metadata:
  name: dynamic-html
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: 5m
    spec:
      containers:
        - image: res-cpe-team-docker-local.artifactory.swg-devops.com/quarkus/dynamic-html:jvm 
          name: benchmark
          env:
            - name: TYPE
              value: "printRetValTypeD"
            - name: JAVA_OPTS_APPEND
              valueFrom:
                configMapKeyRef:
                  name: html-java-env
                  key: JAVA_OPTIONS
