kind: Service
apiVersion: serving.knative.dev/v1
metadata:
  name: graph-bfs
spec:
  template:
    spec:
      containers:
        - image: res-cpe-team-docker-local.artifactory.swg-devops.com/quarkus/graph-bfs:jvm 
          name: benchmark
          env:
            - name: TYPE
              value: "printRetValTypeU"
            - name: JAVA_OPTS_APPEND 
              valueFrom:
                configMapKeyRef:
                  name: bfs-java-env
                  key: JAVA_OPTIONS
