# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: javaopts.cpe.benchmark.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: javaopts-operator 
          name: webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
