apiVersion: v1
kind: Pod
metadata:
  name: driver 
spec:
  serviceAccountName: default
  containers:
    - name: curler
      image: res-cpe-team-docker-local.artifactory.swg-devops.com/quarkus/driver:latest
      command: 
      - "/bin/bash"
      - "-c"
      args:
      - "curl -sSk -H \"Authorization: Bearer $TOKEN\" $APISERVER/api/v1/namespaces/default/pods"
      #- "NAME=$(curl -sSk -H \"Authorization: Bearer $TOKEN\" $APISERVER/api/v1/namespaces/default/pods?labelSelector=app%3D$LABEL | jq .items[0].metadata.name | awk -F\\\" '{print $2}')"
      #- "echo $NAME"
      #- "curl -sSk -H \"Authorization: Bearer $TOKEN\" $APISERVER/api/v1/namespaces/default/pods?labelSelector=app%3D$LABEL | jq .items[0].metadata.name | awk -F\\\" '{print $2}'"
      - "sleep 10000"
